export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [
    'product:list',
    'product:read',
    'product:create',
    'product:update',
    'product:delete',
    'category:list',
    'category:read',
    'category:create',
    'category:update',
    'category:delete',
    'user:list',
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'user:change_role',
    'order:list_all',
    'order:read_any',
    'order:update_status',
    'payment:list',
    'payment:read',
    'payment:create',
    'payment:update_status',
  ],
  cliente: [],
}
